
DROP TABLE IF EXISTS gold.fact_fhv_trip;

-- create fhv and fhvhv fact table

create or replace TABLE nyc_taxi.gold.fact_fhv_trip (
    FHV_TRIP_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
    HVFHS_LICENSE_NUMBER VARCHAR(15),
    DISPATCHING_BASE_NUMBER VARCHAR(15),
    ORIGINATING_BASE_NUMBER VARCHAR(15),
    PU_DATE_ID NUMBER(38,0),
    PU_TIME_ID NUMBER(38,0),
    DO_DATE_ID NUMBER(38,0),
    DO_TIME_ID NUMBER(38,0),
    PU_LOCATION_ID NUMBER(38,0),
    DO_LOCATION_ID NUMBER(38,0),
    SR_FLAG NUMBER(38,0),
    REQUEST_DATE_ID NUMBER(38,0),
    REQUEST_TIME_ID NUMBER(38,0),
    ONSCENE_DATE_ID NUMBER(38,0),
    ONSCENE_TIME_ID NUMBER(38,0),
    ACCESSIBLE_VEHICLE VARCHAR(1),
    TRIP_MILES FLOAT,
    TRIP_TIME FLOAT,
    BASE_PASSENGER_FARE FLOAT,
    TOLLS FLOAT,
    BCF FLOAT,
    SALES_TAX FLOAT,
    CONGESTION_SURCHARGE FLOAT,
    AIRPORT_FEE FLOAT,
    TIPS FLOAT,
    DRIVER_PAY FLOAT,
    SHARED_REQUEST_FLAG VARCHAR(1),
    SHARED_MATCH_FLAG VARCHAR(1),
    ACCESS_A_RIDE_FLAG VARCHAR(1),
    WAV_REQUEST_FLAG VARCHAR(1),
    WAV_MATCH_FLAG VARCHAR(1),
    primary key (FHV_TRIP_ID)
);
